//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace noteblog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public long id { get; set; }
        public Nullable<long> note_category_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public System.DateTime published_at { get; set; }
        public string pic { get; set; }
        public string status { get; set; }
        public int order { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
